Fix copy issue. (#104)
If we run ~1000 step on debug=True, we see

OSError: [Errno 24] Too many open files Traceback (most recent call last): File "/usr/lib/python3.9/multiprocessing/resource_sharer.py", line 138, in _serve File "/usr/lib/python3.9/multiprocessing/connection.py", line 468, in accept File "/usr/lib/python3.9/multiprocessing/connection.py", line 614, in accept File "/usr/lib/python3.9/socket.py", line 29OSError: [Errno 24] Too many open files

Based on pytorch/pytorch#11201, the cause is that the batch gets preserved in the ObjectLogger until it's flushed. With a default buffer size of 1000, we are able to hit the file limit with all the batches that can't be gc-ed yet. Changing the buffer size to 2 makes the problem go away.

The github thread suggests two approaches:

Make a copy of the batch.
https://pytorch.org/docs/master/multiprocessing.html?highlight=sharing%20strategy#sharing-strategies
This PR goes with 1. The implementation is simple and I confirmed offline that I no longer get the "Too many open files" issue. The copy only happens in debug mode. As we normalize some of the tensors, we will also need to copy fewer objects.

Approach 2 does not feel as safe or satisfying. There are a lot of warnings about switching the file mode to file_system in the link provided.

To repro: Amend test_training_batch_logging in builder_trainer_test.py to provide _get_trainer(max_steps=1000)